/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ProcessMonitor;

import java.io.BufferedReader;
import java.io.InputStreamReader;

public class App {
    public static void main(String[] args) {
        try {
            String line;
            Process p = null;
            if (SystemProperty.isWindows()) {
                p = Runtime.getRuntime().exec(System.getenv("windir") +"\\system32\\"+"tasklist.exe");
            } else if (SystemProperty.isLinux()) {
                p = Runtime.getRuntime().exec("ps aho cmd");
            }
            BufferedReader input =
                new BufferedReader(new InputStreamReader(p.getInputStream()));
            while ((line = input.readLine()) != null) {
                System.out.println(line); //<-- Parse data here.
            }
            input.close();
        } catch (Exception err) {
            err.printStackTrace();
        }
    }

}
